var:
  url-repo: https://github.com/ludo2ne/ENSAI-2A-Java   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

author: Ludovic Deneuville

website:
  title: "Java"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#C26521"
    left:
      - href: index.qmd
        text: Home
      - text: Lessons
        menu: 
          - href: doc/cours/01-intro.qmd
            text: "Introduction"
          - href: doc/cours/02-syntax.qmd
            text: "Java Syntax"
          - href: doc/cours/03-collections.qmd
            text: "Collections"
          - href: doc/cours/04-classes.qmd
            text: "Classes"
          - href: doc/cours/05-project.qmd
            text: "Java Project"
          - href: doc/cours/06-junit.qmd
            text: "JUnit"
          - href: doc/cours/07-advanced.qmd
            text: "Advanced Java"
          - href: doc/cours/08-spring.qmd
            text: "Spring Boot"
      - text: Labs
        menu: 
          - href: doc/tp/tp1.qmd
            text: "Lab 1: Password"
          - href: doc/tp/tp2.qmd
            text: "Lab 2: Library"
          - href: doc/tp/tp3.qmd
            text: "Lab 3: Media Player"
          - href: doc/tp/tp4.qmd
            text: "Lab 4: Rated"
          - href: doc/tp/tp5.qmd
            text: "Lab 5: Spring Boot App"
    right:
      - text: Exams
        menu: 
          - href: doc/exam/java-2025.qmd
            text: "Exam 2024-2025"
          - href: doc/exam/java-2025-correction.qmd
            text: "Exam 2024-2025 - Correction"
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme: 
      light: cosmo
      dark: solar
    toc: true
    toc-location: left
    toc-depth: 2
    css: styles.css
  revealjs:
    theme: moon
    slide-number: c/t
    slide-level: 3
    controls: true
    code-line-numbers: false
    css: styles-reveal.css

from: markdown+emoji
lightbox: true
