var:
  url-repo: https://github.com/ludo2ne/ENSAI-2A-Java   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

website:
  title: "Java"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: Lessons
        menu: 
          - href: doc/cours/intro.qmd
            text: "Introduction"
          - href: doc/cours/code.qmd
            text: "Java Syntax"
          - href: doc/cours/collections.qmd
            text: "Collections"
          - href: doc/cours/classes.qmd
            text: "Classes"
          - href: doc/cours/project.qmd
            text: "Java Project"
          - href: doc/cours/junit.qmd
            text: "JUnit"
          - href: doc/cours/advanced.qmd
            text: "Advanced Java"
          - href: doc/cours/spring.qmd
            text: "Spring Boot"
      - text: TP
        menu: 
          - href: doc/tp/tp1.qmd
            text: "TP n°1"
          - href: doc/tp/tp2.qmd
            text: "TP n°2"
          - href: doc/tp/tp3.qmd
            text: "TP n°3"
          - href: doc/tp/tp4.qmd
            text: "TP n°4"
    right:
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme: 
      dark: solar
      light: cosmo
    css: styles.css
  revealjs:
    css: styles-reveal.css
